name: moleculis
description: Moleculis flutter application


version: 0.3.0+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  shared_preferences: ^0.5.8
  flutter_bloc: ^6.0.1
  equatable: ^1.2.3
  easy_localization: ^2.3.2
  google_fonts: ^1.1.0
  package_info: ^0.4.1
  auto_size_text: ^2.1.0
  settings_ui: ^0.3.0
  image_picker: ^0.6.7+4
  cached_network_image: ^2.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/img/launcher/icon.png"
  image_path_android: "assets/img/launcher/icon.png"
  adaptive_icon_background: "assets/img/launcher/background.png"
  adaptive_icon_foreground: "assets/img/launcher/foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/locales/
    - assets/img/
    - assets/img/launcher/