name: moleculis
description: Moleculis flutter application


version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  device_preview: ^0.4.4
  http: ^0.12.1
  shared_preferences: ^0.5.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true