name: moleculis
description: Moleculis flutter application

version: 0.3.0+10

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  http: ^0.13.3
  shared_preferences: ^2.0.6
  flutter_bloc: ^7.0.1
  equatable: ^2.0.2
  easy_localization: ^3.0.0
  google_fonts: ^2.1.0
  package_info: ^2.0.2
  auto_size_text: ^2.1.0
  settings_ui: ^1.0.0
  image_picker: ^0.8.0+3
  cached_network_image: ^3.0.0
  flexible_scrollbar: ^0.1.2
  get_it: ^7.1.3
  firebase_core: ^1.3.0
  cloud_firestore: ^2.2.2
  firebase_storage: ^8.1.3
  freezed_annotation: ^0.14.2
  firebase_database: ^7.1.1
  firebase_messaging: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  build_runner: ^2.0.4
  freezed: ^0.14.2
  json_serializable: ^4.1.3

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/img/launcher/icon.png"
  image_path_android: "assets/img/launcher/icon.png"
  adaptive_icon_background: "assets/img/launcher/background.png"
  adaptive_icon_foreground: "assets/img/launcher/foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/locales/
    - assets/img/
    - assets/img/launcher/